app:
    api:
        prefix: /api/v1
    security:
      expiresIn : 300 # 300 second = 5 minutes


spring:
    secret: fEJ6qu3MQ1pwdpRYxhiXNpor7jNV6tCdhw73m9rR5TfH5rS6Zq1tVDsUooXljGi3
    application:
        name: medical_store
    profiles:
        active: dev